--- 
browny: 
  :id: browny
  :name: Browny
  :picture_id: 12
  :bio: I am twelve weeks old and very playful!
blondie: 
  :id: blondie
  :name: Blondie
  :picture_id: 5
  :bio: I like to take naps.
striped_snake: 
  :id: striped_snake
  :name: Striped snake
  :picture_id: 27
  :bio: I am not a snake.  I'm a young dog.  And I don't have stripes.
gregory: 
  :id: gregory
  :name: Gregory
  :picture_id: "15"
  :bio: Who could resist a puppy with that name?
jinny: 
  :id: jinny
  :name: Jinny
  :picture_id: "17"
  :bio: Hi, I am just born now
maddie: 
  :id: maddie
  :name: Maddie
  :picture_id: "24"
  :bio: I can't bark because I am really shy...
